name: MoArrows
main: com.gmail.l0g1clvl.MoArrows.MoArrows
author: MrAverage
version: 2.4.1
permissions:
    moarrows.use.all:
        default: false
        description: Allows use of all arrow types
    moarrows.bypassmaterials:
        default: false
        description: Eliminates material requirements for user
    moarrows.bypasscooldowns:
        default: false
        description: Eliminates material requirements for user
    moarrows.allowcrit:
        default: false
        description: Allows the user to have critical hits
    moarrows.use.explosive:
        default: false
        description: Allows use of this special arrow
    moarrows.use.compression:
        default: false
        description: Allows use of this special arrow
    moarrows.use.lightning:
        default: false
        description: Allows use of this special arrow
    moarrows.use.poison:
        default: false
        description: Allows use of this special arrow
    moarrows.use.teleport:
        default: false
        description: Allows use of this special arrow
    moarrows.use.razor:
        default: true
        description: Allows use of this special arrow
    moarrows.use.slow:
        default: false
        description: Allows use of this special arrow
    moarrows.use.fire:
        default: false
        description: Allows use of this special arrow
    moarrows.use.net:
        default: false
        description: Allows use of this special arrow
    moarrows.use.doombringer:
        default: false
        description: Allows use of this special arrow
    moarrows.use.piercing:
        default: false
        description: Allows use of this special arrow
    moarrows.reload:
        default: op
        description: Reloads the config file values
    moarrows.help:
        default: false
        description: Allows viewing MoArrows help
    moarrows.list:
        default: false
        description: Allows listing configuration values
    moarrows.command:
        default: false
        description: Allows use of MoArrows command interface
commands:
    moarrows:
        description: The main MoArrows command.
        aliases: [moa]
        usage: /moarrows <list|help>
        permission: moarrows.command
        permission-message: Sorry dude.. you can't use MoArrows commands.