name: MoArrows
main: com.gmail.l0g1clvl.MoArrows.MoArrows
author: MrAverage
version: 1.1.1
permissions:
    moarrows.use.all:
        default: op
        description: Allows use of all arrow types
    moarrows.use.normal:
        default: true
        description: Allows use of normal arrows
    moarrows.use.explosive:
        default: false
        description: Allows use of this special arrows
    moarrows.use.lightning:
        default: false
        description: Allows use of this special arrows
    moarrows.use.water:
        default: false
        description: Allows use of this special arrows
    moarrows.use.poison:
        default: false
        description: Allows use of this special arrows
    moarrows.use.drill:
        default: false
        description: Allows use of this special arrows
    moarrows.use.torch:
        default: false
        description: Allows use of this special arrows
    moarrows.use.animal:
        default: false
        description: Allows use of this special arrows
    moarrows.use.teleport:
        default: false
        description: Allows use of this special arrows
    moarrows.use.razor:
        default: false
        description: Allows use of this special arrows
    moarrows.use.slow:
        default: false
        description: Allows use of this special arrows
    moarrows.free-fees:
        default: false
        description: Bypass iConomy fee cost
    moarrows.free-materials:
        default: op
        description: Bypass extra materials cost
    moarrows.infinite:
        default: false
        description: Will not not consume arrows when firing
    moarrows.set:
        default: false
        description: Allows setting temporary configuration values
    moarrows.help:
        default: true
        description: Allows viewing MoArrows help
    moarrows.list:
        default: true
        description: Allows listing configuration values
    moarrows.command:
        default: true
        description: Allows use of MoArrows command interface
commands:
    moarrows:
        description: The main MoArrows command.
        aliases: [ma]
        usage: /moarrows <list|set|help> or /ma <list|set|help>
        permission: moarrows.command
        permission-message: Sorry dude.. you can't use MoArrows commands.